#ifndef __PIPER_SYNTHESIZER_LOG_COMPONENT_HPP__
#define __PIPER_SYNTHESIZER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(PIPER)

#endif // __PIPER_SYNTHESIZER_LOG_COMPONENT_HPP__
