#ifndef __ESPEAK_SYNTHESIZER_LOG_COMPONENT_HPP__
#define __ESPEAK_SYNTHESIZER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(ESS)

#endif // __ESPEAK_SYNTHESIZER_LOG_COMPONENT_HPP__
