#ifndef VOSK_TRANSCRIPTION_LOG_COMPONENT_HPP__
#define VOSK_TRANSCRIPTION_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(VOSK)

#endif // VOSK_TRANSCRIPTION_LOG_COMPONENT_HPP__
