/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Fri May  2 22:04:10 2025


#include "VoskTranscription_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(VoskTranscriptionParamsCOMPONENT, "yarp.device.VoskTranscription")
}


VoskTranscription_ParamsParser::VoskTranscription_ParamsParser()
{
}


std::vector<std::string> VoskTranscription_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("modelPath");
    params.push_back("sampleRate");
    params.push_back("useGPU");
    return params;
}


bool      VoskTranscription_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(VoskTranscriptionParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter modelPath
    {
        if (config.check("modelPath"))
        {
            m_modelPath = config.find("modelPath").asString();
            yCInfo(VoskTranscriptionParamsCOMPONENT) << "Parameter 'modelPath' using value:" << m_modelPath;
        }
        else
        {
            yCInfo(VoskTranscriptionParamsCOMPONENT) << "Parameter 'modelPath' using DEFAULT value:" << m_modelPath;
        }
        prop_check.unput("modelPath");
    }

    //Parser of parameter sampleRate
    {
        if (config.check("sampleRate"))
        {
            m_sampleRate = config.find("sampleRate").asFloat32();
            yCInfo(VoskTranscriptionParamsCOMPONENT) << "Parameter 'sampleRate' using value:" << m_sampleRate;
        }
        else
        {
            yCError(VoskTranscriptionParamsCOMPONENT) << "Mandatory parameter 'sampleRate' not found!";
            yCError(VoskTranscriptionParamsCOMPONENT) << "Description of the parameter: audio sample rate";
            yCError(VoskTranscriptionParamsCOMPONENT) << "Remember: Units for this parameter are: 'Hz'";
            return false;
        }
        prop_check.unput("sampleRate");
    }

    //Parser of parameter useGPU
    {
        if (config.check("useGPU"))
        {
            m_useGPU = config.find("useGPU").asBool();
            yCInfo(VoskTranscriptionParamsCOMPONENT) << "Parameter 'useGPU' using value:" << m_useGPU;
        }
        else
        {
            yCInfo(VoskTranscriptionParamsCOMPONENT) << "Parameter 'useGPU' using DEFAULT value:" << m_useGPU;
        }
        prop_check.unput("useGPU");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(VoskTranscriptionParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(VoskTranscriptionParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      VoskTranscription_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: VoskTranscription\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'modelPath': path to model directory\n");
    doc = doc + std::string("'sampleRate': audio sample rate\n");
    doc = doc + std::string("'useGPU': use GPU (if supported)\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device VoskTranscription --modelPath <optional_value> --sampleRate 0 --useGPU 0\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device VoskTranscription --sampleRate 0\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
